## get admin privilege
1. run "make me admin" and set the expiring time as long as possible if there is any

## remove pycharm-community & install pycharm-professional
1. from system tray, locate and click "jetbrains toolbox"
2. under the "tools->installed" section, locate "pycharm-community"
3. click the "..." button to the right of "pycharm-community" and select "uninstall"
4. follow the instruction to uninstall pycharm-community
5. under the "tools->available" section, locate "pycharm-professional"
6. click "install" and follow the instruction to install pycharm-professional
7. search and open "pycharm-professional" from start menu
8. in the "license" popup window, choose "activate pycharm" and "get license from jb account"
9. press "log in to jetbrains account" and follow the instruction to login through web browser
10. return to the "license" popup window, press "activate"

## configure pycharm-professional
4. press "create new project" and select "previously configured interpreter"
5. press "..." button on the right side of "previously configured interpreter"
6. select "conda environment" on the left side
7. press "..." button on the right side of "interpreter" and press "show hidden files and folders" on the opened window
8. find "C:\ProgramData\Miniconda3\python.exe" and press OK
9. press "..." button on the right side of "conda executable" and press "show hidden files and folders" on the opened window
10. find "C:\ProgramData\Miniconda3\scripts\conda.exe" and press OK
11. select "make available for all projects" and press OK
12. press OK again to finally open the new project

## test current configurations
1. copy demo.tts.py into the project previously created
2. search and open "pycharm-community" from start menu
3. open the project previously created
4. run the demo.tts.py to get the results

Notes for "demo.tts.py" script:
1. the "os.environ['KMP_DUPLICATE_LIB_OK']='True'" line added is aiming to
   prevent the "duplicated libiomp5md.dll" error. This is an upstream conda design error for
   Windows system (no such error for Linux) and has no fundamental solutions for this yet.
2. we could change the line "device = "cuda" if torch.cuda.is_available() else "cpu""
   into "device = "cpu" if torch.cuda.is_available() else "cpu"" if the GPU memory size is
   not sufficient.
3. a "plt.show()" line is added after "plt.imshow(spec[0].cpu().detach())" to actually show
   the figure, and we need to close the figure to continue running the script.
4. when "unexpected EOF, expected xxxxx more bytes. The file might be corrupted." occurs,
   set "force_reload=True" temporarily for the "waveglow = torch.hub.load" command, to
   re-download the waveglow model
5. the ipython output relies on jupyter notebook environment which is not setup for now.
   If we need the jupyter notebook environment, the following link could be used as reference:
   https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html
